dist: xenial
services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: stable
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
  - "export DISPLAY=:99.0"
  - sleep 3
language: python
python:
- '3.6'
- '3.8'
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - wget -N https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv -f geckodriver /usr/bin
  - sudo chmod +x /usr/bin/geckodriver
jobs:
  include:
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test authentication/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test base/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test booth/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test census/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test mixnet/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test postproc/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test store/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test visualizer/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test voting/ --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
notifications:
  email:
    recipients:
      - marmolpen3@alum.us.es
      - elenamolino99@gmail.com
    on_success: never
    on_failure: always